// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogxylcvxbxmqkmujuhmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9neHlsY3Z4YnhtcWttdWp1aG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODkyOTUsImV4cCI6MjA3MzI2NTI5NX0.jHYGTvPAXMUSA1MBTDpDAwKFLeV6QUsVHHH5OoK-TrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});